# Generated by Django 4.1 on 2022-08-20 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.IntegerField()),
                ('id_productos', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=100)),
                ('pApellido', models.CharField(max_length=100)),
                ('sApellido', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('opinion', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('modo_pagar', models.IntegerField(choices=[(1, 'Tarjeta'), (2, 'Efectivo')])),
                ('total_factura', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mesa', models.CharField(max_length=100)),
                ('disponibilidad', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mesa', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.IntegerField(choices=[(1, 'Cocinando'), (2, 'Listo'), (3, 'En camino'), (4, 'Entregado')])),
                ('total_productos', models.IntegerField()),
                ('delivery', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.IntegerField(choices=[(1, 'Comida'), (2, 'Postre'), (3, 'Bebida'), (4, 'Entrada')])),
                ('tipo', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('disponible', models.BooleanField()),
                ('imagen', models.TextField()),
            ],
        ),
    ]
