# Generated by Django 4.1 on 2022-08-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(default='qwerty123', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='esAutenticado',
            field=models.BooleanField(default=True),
        ),
    ]
